### PR TITLE
Add option to skip recaptcha services in e2e env

### LINKED ISSUE #52: Disable GRecaptcha in e2e tests
Hello, how is everything?

My case involves more performance gains in e2e tests than anything else.
Currently my authentication flows need captcha to work and this is expected for security reasons,
the big question is that using captcha in test environments is very expensive, as it involves downloading the google library,
and generate its configuration (which takes time, mainly in unstable or bad connections as it happens in emerging countries like Brazil - where I am at the moment).

The idea in this case, is to create a kind of "fallback" / "mock" for the GRecaptcha functions so that the fake captcha flows continue to work in test.

What I thought was to add an option:

```js
// controller

isActive = window.ENABLE_RECAPTCHA // (each app will have their owns)
```

```hbs
<GRecaptcha
  @sitekey={{this.recaptchaKey}}
  @onSuccess={{action this.onSuccess}}
  @onExpired={{action this.onExpired}}
  @size="invisible"
  @active={{this.isActive}}
/>
```

With this kind of control, we could only enable recaptcha when is really needed.

PS: I can work on this improvement ;)

### PR DESCRIPTION
**Pull request by brunoocasali**
- Added sinonjs for mocking
- Added basic tests covering `@skip` option usage + normal usage
- Improve testing setup by upgrading base libraries (qunit/qunit-dom etc)

Closes #52

### CODE REVIEW

**Comment by brunoocasali** [comment]
I'll be glad to improve this setup + testing more use cases, this was a `#1 try` only to take the ideas out of my head!

**Comment by brunoocasali** [comment]
This PR makes a HUGE difference in my use cases:

image
image

**Comment by sinankeskin** [comment]
Hey @brunoocasali Thanks for the PR. I'm planning to modernize the addon with latest JS syntax and to the latest LTS. I'll check your PR after and if everything is ok I'll merge.

**Comment by sinankeskin** [comment]
Hey @brunoocasali could you rebase your branch to master and fix the conflict and of course you need to use the skip option from args like @skip

**Comment by brunoocasali** [comment]
Yeah I can do that! 👯

**Comment by brunoocasali** [comment]
Closed, see #76

**Pull request closed without merging**
