### PR TITLE
Update ember-cli 3.1.3 with refact import

### PR DESCRIPTION
**Pull request by eliasmelgaco**
I am updating ember-cli and import refactory

later I will do more tests ;)

ember-cli-babel update #6

### CODE REVIEW

**Comment by eliasmelgaco** [comment]
good evening, @algodave !

Can you look at this PR?

**Comment by algodave** [comment]
@eliasmelgaco Thanks for submitting this upgrade! Shall we also remove `bower.json`?

**Comment by eliasmelgaco** [comment]
Yes, I removed ember and ember-cli-shims. Do you think it necessary to remove all `bower.json`?

Can you test if all the features are correct?

@algodave

**Comment by algodave** [comment]
Everything OK, thanks @eliasmelgaco I'm merging 👍

**Pull request merged**
