### PR TITLE
fix: google-recaptcha script URL query params

### LINKED ISSUE #82: Appending same query param twice in `components/g-recaptcha.js` + unnecessary `&` at the end
You append the same query param on line 65 and then on line 71

On line 66 you're also sometimes adding an empty string for no reason so you end up with an extra `&` at the end of the string in those cases

So in the end you end up with:

```
https://....?explicit=true&onload=...&&onload=...
```

Code should be:

```javascript
  @action
  _initialize(element) {
    const globalName = `__ember_g_recaptcha_${this.elementId}_onload`

    window[globalName] = () => {
      this._render(element)
    }

    let baseUrl = [
      `${this.config['jsUrl'] || 'https://www.google.com/recaptcha/api.js'}?render=explicit`,
      `onload=${globalName}`
    ]

    if (this.config['hl']) {
      baseUrl.push(`hl=${this.config['hl']}`)
    }

    if (!this.options['skip']) {
      this._appendScript(baseUrl.join('&'))
    } else {
      this._render()
    }
  }
```

### PR DESCRIPTION
**Pull request by Pixelik**
closes https://github.com/algonauti/ember-g-recaptcha/issues/82

### CODE REVIEW

**Review by sinankeskin — APPROVED** [review]
Great job @Pixelik Thank you for the contribution.

**Comment by sinankeskin** [comment]
@safeforge let's publish a new version for this change.

**Comment by Pixelik** [comment]
You're welcome! 🙂

**Comment by safeforge** [comment]
@sinankeskin, I don't have permission to publish the current package. We should ping @algodave.

**Comment by Pixelik** [comment]
It should not have been merged. Only 2 out 10 checks were passing. 🤔

**Comment by sinankeskin** [comment]
main branch is ok enough.

image

**Comment by algodave** [comment]
@sinankeskin Version 2.1.1 just published to npmjs.com 

Thanks @Pixelik :tada: 

**Heads-up!** Default branch changed from `master` to `main`

cc @safeforge

**Pull request merged**
