### PR TITLE
fixed recaptcha race condition causing render errors

### PR DESCRIPTION
**Pull request by craig2017**
fixed recaptcha race condition causing render errors

### CODE REVIEW

**Comment by craig2017** [comment]
Can we merge this please?

**Comment by algodave** [comment]
Thanks @craig2017 👍

**Comment by algodave** [comment]
@craig2017 I also published a new version

**Comment by craig2017** [comment]
Thanks!

**Comment by dguayrobotiq** [comment]
Is there a way to have this fix on an older version? I can't upgrade my app to Ember 3.0+ so I'm stuck at `ember-g-recaptcha 0.7.0`

**Comment by craig2017** [comment]
I'm at ember 2.3 and it works fine.

**Comment by dguayrobotiq** [comment]
@craig2017 I'm at ember `2.11.3` and when I update to `ember-g-recaptcha 0.9.0` I get this error:

```
Uncaught Error: Could not find module `@ember/object` imported from `ember-g-recaptcha/configuration`
    at missingModule (loader.js:228)
    at findModule (loader.js:239)
    at Module.findDeps (loader.js:173)
    at findModule (loader.js:243)
    at Module.findDeps (loader.js:173)
    at findModule (loader.js:243)
    at requireModule (loader.js:26)
    at resolveInitializer (index.js:5)
    at registerInitializers (index.js:18)
    at exports.default (index.js:44)
```

**Comment by dguayrobotiq** [comment]
I deleted `node_modules` and reinstalled and it worked. The only thing that I worry about is the note in the release notes for version `0.8.0` here: https://github.com/algonauti/ember-g-recaptcha/releases

`Please note: This requires you app to be upgraded to Ember 3.0 or higher`

Maybe @algodave can chime in?

**Comment by algodave** [comment]
@dguayrobotiq I can confirm that you should upgrade your project to Ember 3+ in order to have that fix - see discussion in #14 and #12

**Pull request merged**
